// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoh-FJEVdhLx2hlJiOCrEORriV7-U9Obg',
    appId: '1:196656160501:web:bdedd5924c2f36b462afbc',
    messagingSenderId: '196656160501',
    projectId: 'd-9-app',
    authDomain: 'd-9-app.firebaseapp.com',
    storageBucket: 'd-9-app.appspot.com',
    measurementId: 'G-PM5YWJQV0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYL1Wo6ZXH0xcrb3z-lki8MsetEARpiA',
    appId: '1:196656160501:android:94490a0025dd6d3262afbc',
    messagingSenderId: '196656160501',
    projectId: 'd-9-app',
    storageBucket: 'd-9-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9LghaUIsEAbUHCyDyM3HbZ6UiaYV2mpA',
    appId: '1:196656160501:ios:c31117d1f41d428362afbc',
    messagingSenderId: '196656160501',
    projectId: 'd-9-app',
    storageBucket: 'd-9-app.appspot.com',
    iosBundleId: 'com.example.d9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9LghaUIsEAbUHCyDyM3HbZ6UiaYV2mpA',
    appId: '1:196656160501:ios:6e81d64b4d4c6f6162afbc',
    messagingSenderId: '196656160501',
    projectId: 'd-9-app',
    storageBucket: 'd-9-app.appspot.com',
    iosBundleId: 'com.example.d9.RunnerTests',
  );
}
